### ISSUE TITLE
Missing in Foundry modules list.

### ISSUE THREAD

**Issue by Weissrolf** [7H3LaughingMan/token-ring-adjuster#1]
Thanks for the module. I posted about it in the Paizo Monster Core tokens discussion. The only thing that seems to be missing is having it listed in the official Foundry modules list to search and find for easy installation. ;-)

**Comment by 7H3LaughingMan** [comment]
I already went through the process to list the module, and the first version has been published. However, it's not visible since the module is still pending review. As soon as it's approved it will be visible.

**Comment by Weissrolf** [comment]
Great, thanks!
